### ISSUE TITLE
process filter error when start sage inferior process

### ISSUE THREAD

**Issue by stardiviner** [stakemori/sage-shell-mode#8] opened 2016-08-08 04:44 UTC
```
error in process filter: Args out of range: "[6D[J[0m[6n[0m[0m[J[0;38;5;21msage: [6D[6C", 65
error in process filter: ansi-color-filter-apply: Args out of range: "[6D[J[0m[6n[0m[0m[J[0;38;5;21msage: [6D[6C", 65
error in process filter: Args out of range: "[6D[J[0m[6n[0m[0m[J[0;38;5;21msage: [6D[6C", 65
```

This is the error message in `*Messages*` buffer when I run `run-sage`.

**Comment by stakemori** [comment] 2016-08-08 04:56
Did you install SageMath by "pacman" on arch linux? If so, this is a duplicate of #7. Currently, I am trying to fix it. And if you build SageMath from the source and use the master branch of SageMath, you will not see this problem.

**Comment by stardiviner** [comment] 2016-08-08 05:01
I see. Thanks.

**Closed** 2016-08-08 05:02 UTC
